import Link from "next/link";
import type { ReactNode } from "react";
export function Header(){const links=[["Program","/founder-cohort"],["Diagnostic","/diagnostic"],["AI Tutor","/ai-tutor"],["For Parents","/parent-webinar"],["Partners","/partners"]];return <header style={{borderBottom:"1px solid #dce5ef",background:"rgba(255,255,255,.94)",position:"sticky",top:0,zIndex:30,backdropFilter:"blur(12px)"}}><div className="container" style={{minHeight:72,display:"flex",alignItems:"center",justifyContent:"space-between",gap:20}}><Link href="/" style={{fontWeight:900,color:"#071b33",letterSpacing:"-.03em"}}><span style={{color:"#155eef"}}>The Digital</span> Tutor</Link><nav style={{display:"flex",gap:22,alignItems:"center",fontSize:14,fontWeight:700,overflowX:"auto"}}>{links.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<Link href="/register?plan=Founder" className="btn btn-primary" style={{minHeight:40,padding:"0 16px"}}>Join cohort</Link></nav></div></header>}
export function Footer(){return <footer className="band" style={{padding:"52px 0 28px"}}><div className="container"><div className="grid grid-3"><div><h3>The Digital Tutor</h3><p style={{color:"#b9c9dc",lineHeight:1.7}}>Affordable accountability for ambitious global students.</p></div><div><h3>Explore</h3><p style={{display:"grid",gap:8,color:"#b9c9dc"}}><Link href="/materials">Materials</Link><Link href="/dashboard">Student dashboard</Link><Link href="/contact">Contact</Link></p></div><div><h3>Launch</h3><p style={{display:"grid",gap:8,color:"#b9c9dc"}}><Link href="/admin">MVP metrics</Link><Link href="/partners">Partnerships</Link><Link href="/parent-webinar">Parent webinar</Link></p></div></div><p style={{borderTop:"1px solid rgba(255,255,255,.14)",paddingTop:24,marginTop:32,color:"#9fb2c9",fontSize:13}}>SAT® is a trademark registered by the College Board, which is not affiliated with and does not endorse The Digital Tutor.</p></div></footer>}
export function CTAButton({href,children,secondary=false}:{href:string;children:ReactNode;secondary?:boolean}){return <Link href={href} className={`btn ${secondary?"btn-secondary":"btn-primary"}`}>{children}</Link>}
export function FeatureCard({index,title,children}:{index:string;title:string;children:ReactNode}){return <article className="card"><div className="icon">{index}</div><h3>{title}</h3><p>{children}</p></article>}
export function PricingCard({name,price,items,href,recommended=false}:{name:string;price:string;items:string[];href:string;recommended?:boolean}){return <article className={`card ${recommended?"recommended":""}`}><span className="eyebrow">{name}</span><div className="price">{price}</div><ul>{items.map(x=><li key={x}>{x}</li>)}</ul><CTAButton href={href}>{name==="Free"?"Start free":name==="Sponsored / NGO"?"Partner with us":name==="Premium"?"Apply for premium":"Join founder cohort"}</CTAButton></article>}
export function PageHero({eyebrow,title,children,actions}:{eyebrow:string;title:string;children:ReactNode;actions?:ReactNode}){return <section className="page-hero"><div className="container"><div className="eyebrow">{eyebrow}</div><h1 className="title" style={{maxWidth:850}}>{title}</h1><div className="lead">{children}</div>{actions&&<div className="actions">{actions}</div>}</div></section>}
export function FAQAccordion({items}:{items:[string,string][]}){return <div>{items.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>}
export function DashboardCard({label,value,detail,progress}:{label:string;value:string;detail?:string;progress?:number}){return <article className="card"><div className="eyebrow">{label}</div><div className="metric">{value}</div>{detail&&<p>{detail}</p>}{progress!==undefined&&<div className="progress"><span style={{width:`${progress}%`}}/></div>}</article>}
export function DisclaimerBanner(){return <div className="note">Independent preparation support. No official affiliation, endorsement, or score guarantee. All practice examples are original.</div>}
